### ISSUE TITLE
Randomize code layout

### ISSUE THREAD

**Issue by FilipAndersson245** [bazhenov/tango#21]
In his talk ["Performance Matters"](https://youtu.be/r-TLSBdHe1A?t=950), Emery Berger talk about the importance of randomizing code layout, heap allocations & stack frame sizes, this to make the data more random and lessen the bias of an individual run. I have a PR open for what I think would randomly change the stack frame offsets. But I had an idea that we could maybe insert a series of NOP operations in the beginning of the benchmark function to offset the code layout, don't know how feasible this is.

**Comment by FilipAndersson245** [comment]
For heap allocation i found this crate, wrapping the default allocator. I'm not that familiar with the allocator API, but I guess this is something the called would have to include otherwise I think it's a nice feature to add here as an optional dependency.
https://docs.rs/shuffling-allocator/latest/shuffling_allocator/

**Comment by bazhenov** [comment]
Thank you for all your contributions. Sorry it took me so long to answer, but right now I'm in the process of moving between countries. It will take some time for me to catch up.

**Comment by FilipAndersson245** [comment]
> Thank you for all your contributions. Sorry it took me so long to answer, but right now I'm in the process of moving between countries. It will take some time for me to catch up.

haha `1h` is quite fine I would say 😂

I also now saw that you had a blog post on this specific topic about code alignment
https://www.bazhenov.me/posts/2024-02-performance-roulette/
very interesting read.

So would you recommend one to specify
`RUSTFLAGS="-C llvm-args=-align-all-functions=6 -C llvm-args=-align-all-nofallthru-blocks=6"`
To ensure less random alignment when compiling benches? If I understand it correct?
