### ISSUE TITLE
Symbol error when trying to run

### ISSUE THREAD

**Issue by FilipAndersson245** [bazhenov/tango#22]
Hello, I am trying to integrate tango into nutshell, but when I add the default factorial bench it breaks when I try to run it.

![image](https://github.com/bazhenov/tango/assets/17986183/17cea9f0-cf34-42f3-b351-0bd84afe76c1)

**Comment by FilipAndersson245** [comment]
I tried the latest dev and got the same error
![image](https://github.com/bazhenov/tango/assets/17986183/a7ce4439-5200-46d0-bde1-10bfbb7408fb)
It seem like it does not build as a dylibrary correctly?

**Comment by FilipAndersson245** [comment]
Is there anything that limits when you can use tango?
I have added the build.rs file
```rs
fn main() {
    println!("cargo:rustc-link-arg-benches=-rdynamic");
    println!("cargo:rerun-if-changed=build.rs");
}
```

**Comment by bazhenov** [comment]
Just to make sure, this is Linux, right? Can you please share the code?

**Comment by FilipAndersson245** [comment]
> Just to make sure, this is Linux, right? Can you please share the code?

Yes this is linux, through (WSL), It worked when I Tested on another repo at least.

https://github.com/FilipAndersson245/nushell/tree/tango

**Comment by bazhenov** [comment]
Ok, I figured it out. In nutshell build script is in `scripts/build.rs` as noted in `Cargo.toml`

```toml
[package]
authors = ["The Nushell Project Developers"]
build = "scripts/build.rs"
```

you need to put println directives in this file. Particularly in non windows version

```rust
#[cfg(not(windows))]
fn main() {
    println!("cargo:rustc-link-arg-benches=-rdynamic");
    println!("cargo:rerun-if-changed=build.rs");
}
```

**Comment by FilipAndersson245** [comment]
Thanks this worked, had totally missed there was already an custom build script, at a non default location :D
