### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by FilipAndersson245** [bazhenov/tango#25]
Hello, just checking in when you belive a new release will be available, we just decided over at https://github.com/nushell/nushell that we would like to move  to tango, but we cannot introduce git dependencies, I built the [PR](https://github.com/nushell/nushell/pull/12469) on the dev branch.

**Comment by bazhenov** [comment]
Thank you for pinging. I'll try to release a new version today. Just need to write release logs.

**Comment by bazhenov** [comment]
v0.5.0 released
