### ISSUE TITLE
macOS Sequoia 15.1 Beta UnableToLoadSymbol

### ISSUE THREAD

**Issue by andrewgazelka** [bazhenov/tango#37]
```
thread 'main' panicked at /Users/andrewgazelka/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tango-bench-0.6.0/src/dylib.rs:62:60:
called `Result::unwrap()` on an `Err` value: UnableToLoadSymbol(DlSym { desc: "dlsym(0x7d0b1660, tango_count): symbol not found" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: bench failed, to rerun pass `--bench paletted_container`
```

https://github.com/andrewgazelka/palette

running

```
cargo bench -- compare
```

**Comment by bazhenov** [comment]
Can you please provide the output of following command:

```console
$ nm -g [path-to-bench-bin] | grep _tango
```

Path to benchmark is usually in `target/release/deps/` and printed by `cargo bench` command before running the benchmark.

**Comment by bazhenov** [comment]
Most probably the problem is that there is no `build.rs` with following content as required by the docs.

```rust
fn main() {
    println!("cargo:rustc-link-arg-benches=-rdynamic");
    println!("cargo:rerun-if-changed=build.rs");
}
```

**Comment by andrewgazelka** [comment]
> ```rust
> fn main() {
>     println!("cargo:rustc-link-arg-benches=-rdynamic");
>     println!("cargo:rerun-if-changed=build.rs");
> }
> ```

Ah yea that looks like it resolved it. Previously seemed like 

```
rustflags = ["-Zexport-executable-symbols"]
```

got away with it on macOS without running the build script but potentially it wasn't applied correctly or macOS changed 🤷‍♂️. Regardless, I was doing it different than the recommended way on macOS anyway, so I will close this.

**Comment by bazhenov** [comment]
One valuable lesson to learn I think is providing clear error messages to the user. I created #38 to address this issue. Thank you for your feedback.

**Comment by TimTimTimTimTimTimTimTimo** [comment]
I'm running into a similar issue on Linux: 
`thread 'main' panicked at /home/USER/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tango-bench-0.6.0/src/dylib.rs:62:60:
called `Result::unwrap()` on an `Err` value: UnableToLoadSymbol(DlSym { desc: "/home/USER/Documents/best-combination/src-tauri/./target/benchmarks/best-combination.patched: undefined symbol: tango_init" })`

My build.rs looks like this: 
```rust
fn main() {
    println!("cargo:rustc-link-arg-benches=-rdynamic");
    println!("cargo:rerun-if-changed=build.rs");
    tauri_build::build()
}
``` 

and the benchmark file like this:
```rust 
use std::hint::black_box;

use best_combination_lib::{
    best_combination_all, best_combination_multi_1, best_combination_multi_2,
    best_combination_single, load_data,
};
use betting_game_data::Data;
use tango_bench::*;

fn best_combination_benchmarks() -> impl IntoBenchmarks {
    let data: &'static Data = Box::leak(Box::new(load_data()));

    return [
        benchmark_fn("benchmark_single", |b| {
            b.iter(|| best_combination_single(black_box(data)))
        }),
        benchmark_fn("benchmark_multi_1", |b| {
            b.iter(|| best_combination_multi_1(black_box(data)))
        }),
        benchmark_fn("benchmark_all", |b| {
            b.iter(|| best_combination_all(black_box(data)))
        }),
        benchmark_fn("benchmark_multi_2", |b| {
            b.iter(|| best_combination_multi_2(black_box(data)))
        }),
    ];
}

tango_benchmarks!(best_combination_benchmarks());
tango_main!();
```

I'm running:
`cargo export target/benchmarks -- bench --bench=best-combination`  and then `cargo bench -q --bench=best-combination -- compare ./target/benchmarks/best-combination` similar to the example in the README.

I'm not very familiar with dynamic linking and this CLI, so any help would be appreciated!
